name: sqlite3_vec_example
description: "Demonstrates how to use the sqlite3_vec plugin."

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  sqlite3_vec:
    path: ../
  sqlite3: ^2.7.5
  sqlite3_flutter_libs: ^0.5.31

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true