targets:
  $default:
    builders:
      drift_dev:
        # These options change how drift generates code
        options:
          skip_verification_code: true
          data_class_to_companions: false
          named_parameters: true
          sql:
            dialect: sqlite
            options:
              version: "3.45"
              known_functions:
                lexo_rank_next: "text (int, text null)"
                lexo_rank_previous: "text (int, text null)"
                lexo_rank_reorder_after: "text (text null, text null)"
              modules:
                - json1
                - fts5
      json_serializable:
        options:
          explicit_to_json: true