name: Flutter CICD # action name

on:
  push:
    tags:
      - "v*"

jobs:
  build: # job's name
    runs-on: ubuntu-latest # container os
    env: # ADD environment variables
      KEY_JKS: ${{ secrets.KEY_JKS }}
      KEY_PATH: ${{ github.workspace }}/key.jks
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
    defaults:
      run:
        working-directory: app
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build container proxy
        working-directory: packages/flutter_mozilla_components/javascript/container_proxy
        run: |
          npm i
          npx webpack
      - name: Create key file
        run: echo $KEY_JKS | base64 -di > $KEY_PATH
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.4
      - run: dart pub global activate melos
      - run: melos bs
      # - run: flutter test
      - run: flutter build apk --release --split-per-abi --no-tree-shake-icons
      - run: flutter build appbundle
      - name: Create github artifact release # disable this to save storage
        uses: ncipollo/release-action@v1
        with:
          artifacts: "app/build/app/outputs/apk/release/*.apk,app/build/app/outputs/bundle/release/app-release.aab"
      - name: Upload app bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: appbundle
          path: app/build/app/outputs/bundle/release/app-release.aab
